code-insiders --install-extension Equinusocio.vsc-material-theme
code-insiders --install-extension PeterJausovec.vscode-docker
code-insiders --install-extension dbaeumer.vscode-eslint
code-insiders --install-extension esbenp.prettier-vscode
code-insiders --install-extension flowtype.flow-for-vscode
code-insiders --install-extension freebroccolo.reasonml
code-insiders --install-extension mohsen1.prettify-json
code-insiders --install-extension patrys.vscode-code-outline
code-insiders --install-extension robertohuertasm.vscode-icons
code-insiders --install-extension robinbentley.sass-indented
code-insiders --install-extension teabyii.ayu
code-insiders --install-extension vscodevim.vim
code-insiders --install-extension xabikos.ReactSnippets
