# Taps
tap "datawire/blackbird"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"

# Packages
brew "ack"
brew "python"
brew "awscli"
brew "bash"
brew "fontconfig"
brew "gettext"
brew "cairo"
brew "coreutils"
brew "ctags"
brew "docker"
brew "exa"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "go"
brew "gotags"
brew "graphicsmagick"
brew "grep"
brew "gzip"
brew "highlight"
brew "hugo"
brew "kubernetes-cli"
brew "kubectx"
brew "maven"
brew "neovim", args: ["HEAD"]
brew "nginx"
brew "node"
brew "nodenv"
brew "pango"
brew "postgresql"
brew "python@2"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "rename"
brew "ruby"
brew "swiftlint"
brew "the_silver_searcher"
brew "tidy-html5"
brew "tig"
brew "tmux"
brew "unrar"
brew "watchman"
brew "weechat", args: ["with-aspell", "with-curl", "with-lua", "with-perl", "with-ruby"]
brew "yarn"
brew "youtube-dl"
brew "zplug"
brew "zsh"
brew "datawire/blackbird/telepresence"
brew mas

# Casks
cask "osxfuse"
cask "1password"
cask "alfred"
cask "bartender"
cask "cheatsheet"
cask "dash"
cask "docker"
cask "dropbox"
cask "figma"
cask "firefox-nightly"
cask "font-hack"
cask "imageoptim"
cask "istat-menus"
cask "iterm2-nightly"
cask "kitematic"
cask "nightowl"
cask "oracle-jdk"
cask "rocket"
cask "setapp"
cask "slack"
cask "soundcleod"
cask "spotify"
cask "transmit"
cask "tripmode"
cask "typora"
cask "viscosity"
cask "visual-studio-code-insiders"

# Mac App Store
mas "Kindle", id: 405399194
mas "Pastebot", id: 1179623856
mas "Xcode", id: 497799835
mas "Fantastical", id: 975937182
mas "Napkin", id: 581789185
mas "Keynote", id: 409183694
mas "Bear", id: 1091189122
mas "Things", id: 904280696
mas "Blocker", id: 1107421413
mas "Deliveries", id: 924726344
mas "Tweetbot", id: 1384080005
mas "Pixelmator", id: 407963104
mas "Divvy", id: 413857545
mas "Gapplin", id: 768053424
