###
# Taps
###
tap "datawire/blackbird"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

cask_args appdir: "/Applications"

###
# Casks
###
cask "osxfuse"
cask "1password"
cask "alfred"
cask "bartender"
cask "cheatsheet"
cask "dash"
cask "docker"
cask "minikube"
cask "dropbox"
cask "kitty"
cask "figma"
cask "firefox"
cask "font-hack"
cask "imageoptim"
cask "istat-menus"
cask "kitematic"
cask "nightowl"
cask "rocket"
cask "setapp"
cask "slack"
cask "soundcleod"
cask "spotify"
cask "transmit"
cask "typora"
cask "viscosity"
cask "visual-studio-code-insiders"

###
# Mac App Store
###
mas "Kindle", id: 405399194
mas "Pastebot", id: 1179623856
mas "Xcode", id: 497799835
mas "Fantastical", id: 975937182
mas "Napkin", id: 581789185
mas "Keynote", id: 409183694
mas "Things", id: 904280696
mas "Blocker", id: 1107421413
mas "Deliveries", id: 924726344
mas "Tweetbot", id: 1384080005
mas "Pixelmator Pro", id: 1289583905
mas "Divvy", id: 413857545
mas "Gapplin", id: 768053424

###
# Packages
###

# Command Line Utilities
brew "rename"
brew "gettext"
brew "fontconfig"
brew "schollz/tap/croc"
brew "coreutils"
brew "exa"
brew "grep"
brew "ripgrep"
brew "gzip"
brew "highlight"
brew "gnu-sed"
brew "lsd"
brew "up"
brew "watchman"
brew "delta"

brew "bash"
brew "zsh"
brew "zplug"

brew "unrar"
brew "youtube-dl"

brew "neovim"
brew "tmux"
brew "reattach-to-user-namespace"

# Programming languages
brew "yarn"
brew "node"
brew "nodenv"

brew "pyenv"

brew "go"
brew "gotags"
brew "protobuf"

brew "tflint"

brew "clang-format"
brew "cairo"
brew "cuelang/tap/cue"
brew "graphicsmagick"

brew "ruby"
brew "rbenv"

brew "pgformatter"
brew "rustup-init"
brew "swiftlint"
brew "tidy-html5"

# Developer Tooling
brew "git"
brew "git-lfs"
brew "tig"
brew "hub"
brew "github/gh/gh"
brew "httpie"
brew "docker"
brew "hyperkit"

# Developer Infrastructure Tooling
brew "awscli"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "argoproj/tap/argocd"
brew "datawire/blackbird/telepresence"
brew "kubie"
brew "derailed/k9s/k9s"
brew "terraform"
