brew cask install dropbox
brew cask install alfred
brew cask install bartender
brew cask install cheatsheet
brew cask install font-hack
brew cask install viscosity
brew cask install vistual-studio-code-insiders
brew cask isntall setapp
brew cask install 1password
