printWidth: 80
tabWidth: 2
useTabs: false
singleQuote: false
proseWrap: "never"

overrides:
  - files: "*.md"
    options:
      parser: "markdown"
  - files: "*.yaml"
    options:
      parser: "yaml"
