printWidth: 80
tabWidth: 2
useTabs: true
singleQuote: true
proseWrap: "never"

overrides:
  - files: "*.md"
    options:
      parser: "markdown"
  - files: "*.yaml"
    options:
      parser: "yaml"
      proseWrap: preserve
      singleQuote: false
  - files: "*.yml"
    options:
      parser: "yaml"
      proseWrap: preserve
      singleQuote: false
