# We are using xterm
export TERM="xterm-256color"

# Dotilfes
export DOTFILES="$HOME/.dotfiles"

# Set $ZDOTDIR
export ZDOTDIR="$HOME/.zsh"

# Load zplug
export ZPLUG_HOME=/usr/local/opt/zplug

# Zsh functions
export ZFUNCTIONS="${ZDOTDIR:-~}/.zshfunc"
mkdir -p $ZFUNCTIONS
fpath+=$ZFUNCTIONS

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
